In [12]:
import pandas as pd
import utils
import os

In [17]:
root_path = '/Users/saurabh/PycharmProjects/IDS/final_project/music-genre-classification/data/2018655052_small'
tracks_dict = {}
for path, subdirs, files in os.walk(root_path):
    for name in files:
        if name.split('.')[0].isdigit():
            tracks_dict[int(name.split('.')[0])] = os.path.join(path, name)
track_id_list = tracks_dict.keys()
track_id_set = set(track_id_list)

In [25]:
tracks = utils.load('./data/fma_metadata/tracks.csv')
tracks.head()

            album                                                          \
         comments        date_created date_released engineer favorites id
track_id
2               0 2008-11-26 01:44:45    2009-01-05      NaN         4  1
3               0 2008-11-26 01:44:45    2009-01-05      NaN         4  1
5               0 2008-11-26 01:44:45    2009-01-05      NaN         4  1
10              0 2008-11-26 01:45:08    2008-02-06      NaN         4  6
20              0 2008-11-26 01:45:05    2009-01-06      NaN         2  4

                                                                           \
                                        information listens producer tags
track_id
2                                           <p></p>    6073      NaN   []
3                                           <p></p>    6073      NaN   []
5                                           <p></p>    6073      NaN   []
10                                              NaN   47632      NaN   []
20        <p> "spiritual songs" from Nicky Cook</p>    2710      NaN   []

          ...       track                         \
          ... information interest language_code
track_id  ...
2         ...         NaN     4656            en
3         ...         NaN     1470            en
5         ...         NaN     1933            en
10        ...         NaN    54881            en
20        ...         NaN      978            en

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN


         number publisher tags            title
track_id
2             3       NaN   []             Food
3             4       NaN   []     Electric Ave
5             6       NaN   []       This World
10            1       NaN   []          Freeway
20            3       NaN   []  Spiritual Level

[5 rows x 52 columns]

In [26]:
tracks = tracks['track'][['genre_top', 'title']]
tracks = tracks.loc[track_id_list]

In [34]:
tracks = tracks.rename(columns = {'genre_top': 'genre'})
tracks.head()

                 genre                            title
track_id
135054    Experimental  Hari Karl (for Larry Eisenberg)
135336             Pop                  Slow and Steady
135337             Pop        The Dream and the Dreamer
135043            Folk                            Babel
135091    Experimental                    Tree and Wind

In [35]:
tracks['genre'].value_counts()

Rock                   1000
Pop                    1000
International          1000
Instrumental           1000
Hip-Hop                1000
Folk                   1000
Experimental           1000
Electronic             1000
Spoken                    0
Soul-RnB                  0
Old-Time / Historic       0
Jazz                      0
Easy Listening            0
Country                   0
Classical                 0
Blues                     0
Name: genre, dtype: int64

In [38]:
tracks['genre'] = tracks['genre'].cat.remove_unused_categories()

In [39]:
tracks['genre'].value_counts()

Rock             1000
Pop              1000
International    1000
Instrumental     1000
Hip-Hop          1000
Folk             1000
Experimental     1000
Electronic       1000
Name: genre, dtype: int64

In [40]:
tracks.to_csv('./data/final_tracks.csv')